# [NUEVO]
import flet as ft  # [NUEVO]


# [NUEVO]
def mostrar_dialogo_confirmacion(  # [NUEVO]
    page: ft.Page,  # [NUEVO]
    titulo: str,  # [NUEVO]
    mensaje: str,  # [NUEVO]
    on_confirmar,  # [NUEVO]
    on_cancelar=None  # [NUEVO]
):  # [NUEVO]
    """Muestra un modal AlertDialog insertándolo en page.overlay."""  # [NUEVO]

    def cerrar_dialogo(e=None):  # [NUEVO]
        dialogo.open = False  # [NUEVO]
        page.update()  # [NUEVO]
        if on_cancelar:  # [NUEVO]
            on_cancelar()  # [NUEVO]

    def confirmar_accion(e=None):  # [NUEVO]
        dialogo.open = False  # [NUEVO]
        page.update()  # [NUEVO]
        if on_confirmar:  # [NUEVO]
            on_confirmar()  # [NUEVO]

    dialogo = ft.AlertDialog(  # [NUEVO]
        modal=True,  # [NUEVO]
        title=ft.Row(  # [NUEVO]
            controls=[  # [NUEVO]
                ft.Icon(ft.Icons.WARNING_AMBER_ROUNDED, color=ft.Colors.AMBER_400, size=28),  # [NUEVO]
                ft.Text(titulo, weight=ft.FontWeight.BOLD, color=ft.Colors.WHITE, size=18)  # [NUEVO]
            ],  # [NUEVO]
            spacing=10  # [NUEVO]
        ),  # [NUEVO]
        content=ft.Text(mensaje, color=ft.Colors.BLUE_GREY_100, size=14),  # [NUEVO]
        bgcolor=ft.Colors.BLUE_GREY_800,  # [NUEVO]
        actions=[  # [NUEVO]
            ft.TextButton("Cancelar", on_click=cerrar_dialogo, style=ft.ButtonStyle(color=ft.Colors.BLUE_GREY_200)),  # [NUEVO]
            ft.ElevatedButton(  # [NUEVO]
                "Eliminar",  # [NUEVO]
                icon=ft.Icons.DELETE_FOREVER,  # [NUEVO]
                bgcolor=ft.Colors.RED_700,  # [NUEVO]
                color=ft.Colors.WHITE,  # [NUEVO]
                on_click=confirmar_accion  # [NUEVO]
            ),  # [NUEVO]
        ],  # [NUEVO]
        actions_alignment=ft.MainAxisAlignment.END,  # [NUEVO]
    )  # [NUEVO]

    # Insertar el diálogo en page.overlay antes de abrirlo  # [NUEVO]
    page.overlay.append(dialogo)  # [NUEVO]
    dialogo.open = True  # [NUEVO]
    page.update()  # [NUEVO]